version: "3"
services:
  app:
    build:
      dockerfile: ./app.dockerfile
      context: .
    container_name: app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    links:
      - api
    depends_on:
      - api
  api:
    build:
      dockerfile: ./flask.dockerfile
      context: .
    container_name: api
    volumes:
      - ./api:/home/blackjeck
    ports:
      - "5000:5000"