version: "3"
services:
  api:
    build:
      dockerfile: ./flask.dockerfile
      context: .
    volumes:
      - ./api:/home/blackjeck
    ports:
      - "5000:5000"
  app:
    build:
      dockerfile: ./app.dockerfile
      context: .
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"